# Generated by Django 3.1.7 on 2021-05-01 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Goods_Name', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Order_Date', models.DateTimeField(blank=True, null=True)),
                ('Delivery_Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Goods_Name', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Order_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Delivery_Date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
